name: WindowsServer Builds
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cxx_standard: [23]
        build_type: [
            {"BUILD_TYPE":"Release", "RUNTIME":"MD"},
            {"BUILD_TYPE":"Debug",   "RUNTIME":"MDd"}
        ]
        configuration: [
          {"WINDOWS_VERSION":"2019", "TOOLCHAIN_VERSION":"16"},
          {"WINDOWS_VERSION":"2022", "TOOLCHAIN_VERSION":"17"}
        ]

    runs-on: windows-${{matrix.configuration.WINDOWS_VERSION}}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
#          set-safe-directory: ''

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: lukka/get-cmake@latest  # <--= Just this one-liner suffices.
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Check system dependencies after checkout
        run: |
          python3 --version
          cmake --version
          ninja --version
          cl
          python3 -m pip install --no-cache-dir --break-system-packages conan==1.63
          conan --version

      - name: Configure CMake
        env:
          CC: cl
          CXX: cl
          BUILD_TYPE: ${{matrix.build_type.BUILD_TYPE}}
          RUNTIME: ${{matrix.build_type.RUNTIME}}
          TOOLCHAIN_VERSION: ${{matrix.configuration.TOOLCHAIN_VERSION}}
          CXX_STANDARD: ${{matrix.cxx_standard}}
        run: |
          New-Item -Path "./" -Name local_build -ItemType "directory"

          cmake -B local_build -GNinja -DCMAKE_BUILD_TYPE:STRING="$Env:BUILD_TYPE" -DCMAKE_RUNTIME:STRING="$Env:RUNTIME" -DCMAKE_CXX_STANDARD:STRING="$Env:CXX_STANDARD"

      - name: Build
        run: cmake --build local_build

#      - name: Test
#        working-directory: local_build
#        run: ctest --rerun-failed --output-on-failure
